### ISSUE TITLE
Catch promise errors

### ISSUE THREAD

**Issue by nfroidure** [1000ch/reachable-urls#1]
You should catch promises errors here and exit with 1:
https://github.com/1000ch/reachable-urls/blob/master/cli.js#L117

Currently when an error happens the process runs indefinitely.

**Comment by 1000ch** [comment]
Also fixed by 2ed48d1.

**Comment by nfroidure** [comment]
The error is caught but sine there is no process.exit, the process will not end with an error code which is probably not what you want, by example, when using in a CI as tests as i plan to.

**Comment by 1000ch** [comment]
Fixed again 242fa0e.
